CREATE TABLE users(
	id INTEGER NOT NULL PRIMARY KEY,
	username VARCHAR(32) NOT NULL,
	password VARCHAR(32) NOT NULL)

CREATE TABLE event(
	id INTEGER NOT NULL PRIMARY KEY,
	event VARCHAR(32) NOT NULL,
	note VARCHAR(32) NOT NULL)