CREATE TABLE users(
	id VARCHAR(36) NOT NULL PRIMARY KEY,
	username VARCHAR(32) NOT NULL,
	password VARCHAR(32) NOT NULL)

CREATE TABLE event(
	id VARCHAR(36) NOT NULL PRIMARY KEY,
	
	event VARCHAR(32) NOT NULL,
	note VARCHAR(32) NOT NULL)